### ISSUE TITLE
Authentication protocol EMV3DS missing

### ISSUE THREAD

**Issue by facine** [CommerceRedsys/sermepa#16]
Operacion de autenticacion rechazada, datos DS_MERCHANT_EMV3DS no está indicado o es demasiado grande y no se puede convertir en JSON

**Comment by zapamix** [comment]
Hola, tenemos un site en Drupal 8 con Commerce 2.21 y tenemos el mismo problema con esta librería. Nos urge solucionar el problema, podemos ayudar de alguna manera?
Gracias.

**Comment by zapamix** [comment]
El valor de la variable $this->DsMerchantEMV3DS es un array vacío.

Línea 426 'src/Sermepa.php':

'Ds_Merchant_EMV3DS' => $this->DsMerchantEMV3DS,

Creo que con esta modificación funcionaría:

Línea 446 'src/Sermepa.php':

return array_filter($parameters, function($parameter) {
      return ($parameter !== NULL && $parameter !== FALSE && $parameter !== '' && **!empty($parameter)**);
    });

[mypatch.zip](https://github.com/CommerceRedsys/sermepa/files/5333993/mypatch.zip)

**Comment by facine** [comment]
Fixed.
